export const ADD_TEXT_LIST = "ADD_TEXT_LIST";
export const SORT_TEXT_LIST = "SORT_TEXT_LIST";
export const REMOVE_TEXT_LIST = "REMOVE_TEXT_LIST";
export const SELECT_FILTER_COLOR = "SELECT_FILTER_COLOR";
export const SELECT_HIGHLIGHTER_COLOR = "SELECT_HIGHLIGHTER_COLOR";
